"""add config column to flow table

Revision ID: 22bdbce9dc18
Revises: 02c49f2fa2ea
Create Date: 2025-09-23 11:43:01.426042

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "22bdbce9dc18"
down_revision: str | Sequence[str] | None = "02c49f2fa2ea"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("flow", schema=None) as batch_op:
        batch_op.add_column(sa.Column("config", sqlite.JSON(), nullable=False))

    with op.batch_alter_table("run", schema=None) as batch_op:
        batch_op.alter_column(
            "status",
            existing_type=sa.VARCHAR(length=14),
            server_default=None,
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("run", schema=None) as batch_op:
        batch_op.alter_column(
            "status",
            existing_type=sa.VARCHAR(length=14),
            server_default=sa.text("'pending'"),
            existing_nullable=False,
        )

    with op.batch_alter_table("flow", schema=None) as batch_op:
        batch_op.drop_column("config")

    # ### end Alembic commands ###
