"""event status update

Revision ID: 427444eb5d2c
Revises: c86fdf272815
Create Date: 2025-09-29 13:36:08.796604

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "427444eb5d2c"
down_revision: str | Sequence[str] | None = "c86fdf272815"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("event", schema=None) as batch_op:
        batch_op.alter_column(
            "type",
            existing_type=sa.VARCHAR(length=15),
            type_=sa.Enum(
                "status",
                "log",
                "step_start",
                "step_end",
                "checkpoint",
                "prompt",
                "artifact",
                "screenshot",
                "error",
                name="eventtype",
            ),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("event", schema=None) as batch_op:
        batch_op.alter_column(
            "type",
            existing_type=sa.Enum(
                "status",
                "log",
                "step_start",
                "step_end",
                "checkpoint",
                "prompt",
                "artifact",
                "screenshot",
                "error",
                name="eventtype",
            ),
            type_=sa.VARCHAR(length=15),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
