"""Initial schema creation with SQLModel

Revision ID: b9f712cd6fa9
Revises:
Create Date: 2025-09-19 03:27:51.964387

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b9f712cd6fa9"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("email", sa.VARCHAR(), nullable=False),
        sa.Column("name", sa.VARCHAR(), nullable=True),
        sa.Column("role", sa.VARCHAR(), nullable=False),
        sa.Column("id", sa.CHAR(32), nullable=False),
        sa.Column("password_hash", sa.VARCHAR(), nullable=False),
        sa.Column("created_at", sa.DATETIME(), nullable=False),
        sa.Column("updated_at", sa.DATETIME(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.create_table(
        "flow",
        sa.Column("key", sa.VARCHAR(), nullable=False),
        sa.Column("name", sa.VARCHAR(), nullable=False),
        sa.Column("description", sa.VARCHAR(), nullable=True),
        sa.Column("config", sqlite.JSON(), nullable=False),
        sa.Column("id", sa.CHAR(32), nullable=False),
        sa.Column("created_at", sa.DATETIME(), nullable=False),
        sa.Column("updated_at", sa.DATETIME(), nullable=False),
        sa.Column("created_by", sa.CHAR(32), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_flow_created_by"), "flow", ["created_by"], unique=False)
    op.create_index(op.f("ix_flow_key"), "flow", ["key"], unique=True)
    op.create_table(
        "run",
        sa.Column("status", sa.VARCHAR(), nullable=False),
        sa.Column("started_at", sa.DATETIME(), nullable=True),
        sa.Column("ended_at", sa.DATETIME(), nullable=True),
        sa.Column("error", sa.VARCHAR(), nullable=True),
        sa.Column("result_uri", sa.VARCHAR(), nullable=True),
        sa.Column("id", sa.CHAR(32), nullable=False),
        sa.Column("created_at", sa.DATETIME(), nullable=False),
        sa.Column("updated_at", sa.DATETIME(), nullable=False),
        sa.Column("flow_id", sa.CHAR(32), nullable=False),
        sa.Column("user_id", sa.CHAR(32), nullable=False),
        sa.ForeignKeyConstraint(["flow_id"], ["flow.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "event",
        sa.Column("type", sa.VARCHAR(), nullable=False),
        sa.Column("message", sa.VARCHAR(), nullable=True),
        sa.Column("payload", sqlite.JSON(), nullable=False),
        sa.Column("at", sa.DATETIME(), nullable=False),
        sa.Column("id", sa.CHAR(32), nullable=False),
        sa.Column("run_id", sa.CHAR(32), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["run.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "session",
        sa.Column("browser_provider_session_id", sa.VARCHAR(), nullable=True),
        sa.Column("status", sa.VARCHAR(), nullable=False),
        sa.Column("session_url", sa.VARCHAR(), nullable=True),
        sa.Column("created_at", sa.DATETIME(), nullable=False),
        sa.Column("ended_at", sa.DATETIME(), nullable=True),
        sa.Column("id", sa.CHAR(32), nullable=False),
        sa.Column("run_id", sa.CHAR(32), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["run.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("session")
    op.drop_table("event")
    op.drop_table("run")
    op.drop_index(op.f("ix_flow_key"), table_name="flow")
    op.drop_index(op.f("ix_flow_created_by"), table_name="flow")
    op.drop_table("flow")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_table("user")
    # ### end Alembic commands ###
